# Generated by Django 5.1.1 on 2024-09-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='user',
            new_name='owner',
        ),
    ]
