# Generated by Django 5.1.1 on 2024-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_advertisementview'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
