# Generated by Django 5.1.1 on 2026-09-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_alter_rating_options_advertisementreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementReview',
        ),
    ]
