# Generated by Django 5.1.1 on 2026-09-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_delete_advertisementreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at']},
        ),
    ]
